# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'some' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for some
  pod 'SnapKit', '~> 5.0.0'
  target 'someTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'someUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
